### PR TITLE
Html5routes

### PR DESCRIPTION
**Pull request by jshor**
this updates the routes and all links to use html5 routes

example: `http://localhost:8001/#/details/1` is now:  `http://localhost:8001/details/1`

the modrewrite excludes the `/api` and `/auth` paths and also excludes any url having a dot in it (to allow .js, .css, etc files to not redirect to `/`)

### CODE REVIEW

**Comment by yx296** [comment]
does your logout work

**Comment by jshor** [comment]
@yx296 hm, it doesn't, but oddly if I manually type in `/auth/logout`, it does... i'll have to look into it

**Comment by yx296** [comment]
I took out the 
 $routeProvider.otherwise({redirectTo: '/'});

in index.js in list, and it went to http://localhost:8001/auth/logout, but it just stays there on a blank white page, if you refresh it does log you out and goes to logged out.

**Comment by jshor** [comment]
@yx296 fixed

**Comment by yx296** [comment]
LGTM

**Pull request merged**
