### PR TITLE
Vivace 213

### PR DESCRIPTION
**Pull request by Shuffguy**
Comment authors are now stored on comment entries in a consistent format, without domain names.

### CODE REVIEW

**Comment by jackofseattle** [comment]
Are you going to fix all of the existing format issues?

**Comment by Shuffguy** [comment]
This is the only one I'm aware of, but I can fix others if you have others in mind.

**Comment by jackofseattle** [comment]
I meant fixing the entries that are already in the database.   Or are you going to just leave the conversion logic in place for the historical entries?

**Comment by Shuffguy** [comment]
I hadn't planned on modifying the current data, just to introduce this code so we have consistency going forward.

**Comment by jackofseattle** [comment]
LGTM

**Pull request merged**
